FROM python:3.12-slim
WORKDIR /app
COPY pyproject.toml .
COPY requirements.txt .
COPY src ./src
COPY tests ./tests
RUN pip install --no-cache-dir -e .
RUN pip install --no-cache-dir pytest
CMD ["python", "-m", "pytest", "-v"]
